docker image: change openjdk11 with alpine to debianslim with arm64 support
Consensys-Incorporated/tessera pull request #1443
Opened 2022-04-08 07:04 UTC by baptiste-b-pegasys

## PR Description

In order to use tessera on the mac m1 (with the arm processor), the docker image has to support the arm64 architecture.

The current openjdk11:alpine doesn't support arm64, but the openjdk11:debianslim does.

## Fixed Issue(s)

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

2022-04-08 07:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/ConsenSys/tessera?pullRequest=1443) <br/>All committers have signed the CLA.

2022-04-08 11:38 UTC, Krish1979 approved these changes

2022-04-20 03:32 UTC, macfarla approved these changes

2022-04-20 08:56 UTC, chris-j-h requested changes
Using this base considerably increases the size of the image

```
quorumengineering/quorum   debianslim           29aeeb54d1ba   33 seconds ago   468MB
quorumengineering/quorum   latest               79024fb87590   12 days ago      88.5MB
```

Perhaps it would be better to create a separate m1 image if this is the only option, instead of incurring a large storage hit on all other users?

2022-04-21 14:36 UTC, baptiste-b-pegasys commented
88MB for a JVM is pretty low, I think you are comparing goquorum with tessera

`adoptopenjdk/openjdk11       alpine        16e2d39c5bca   45 hours ago    342MB`

2022-04-22 10:12 UTC, chris-j-h approved these changes

2022-04-22 10:12 UTC, chris-j-h commented
> 88MB for a JVM is pretty low, I think you are comparing goquorum with tessera
> 
> `adoptopenjdk/openjdk11 alpine 16e2d39c5bca 45 hours ago 342MB`

right you are - typo when building the image :)

2022-04-26 06:49 UTC, merged