Enclave over WebSockets
Consensys-Incorporated/tessera pull request #623
Opened 2019-02-06 16:39 UTC by melowe

Currently dormant module enabling the remoting of enclave over WebSockets in the same way as enclave-jaxws remotes over rest/http. EnclaveEndpointTest fires up local WebSockets server and delegates to mocked enclave instance.

2019-02-08 09:43 UTC, prd-fox requested changes

2019-02-08 09:43 UTC, prd-fox commented on enclave/enclave-api/src/main/java/com/quorum/tessera/enclave/AlwaysSendToHelper.java
> +package com.quorum.tessera.enclave;
What issue is this really addressing? What was wrong about the configuration passing in the list directly? 

As far as I can see, the configuration object is still in scope for both the main application and the standalone enclave, so it's not a scoping issue. This also just sits in-between the config and the key converter, so it doesn't seem to be a circular reference issue either.

2019-02-08 09:43 UTC, prd-fox commented on enclave/enclave-api/src/main/resources/tessera-enclave-spring.xml
> +    <bean id="alwaysSendToHelper" class="com.quorum.tessera.enclave.AlwaysSendToHelper">
Pending above issue, this could be removed.

2019-02-08 09:43 UTC, prd-fox commented on enclave/enclave-api/src/test/java/com/quorum/tessera/enclave/AlwaysSendToHelperTest.java
> +package com.quorum.tessera.enclave;
Pending above issue, this could be removed.

2019-02-08 09:43 UTC, prd-fox commented on enclave/enclave-websockets/pom.xml
> +        <dependency>
Is there a reason use this server instead of the Jersey-Grizzly test server used elsewhere?

2019-02-08 09:43 UTC, prd-fox commented on enclave/enclave-websockets/src/main/java/com/jpmorgan/quorum/enclave/websockets/EnclaveAdapter.java
> +        return client.pollForResult(ByteBuffer.class).get().array();
Are you sure that a ByteBuffer is the returned object? It looks like under the hood it sends the byte array, which is what we should be receiving.

2019-02-08 09:43 UTC, prd-fox commented on enclave/enclave-websockets/src/main/java/com/jpmorgan/quorum/enclave/websockets/EnclaveAdapter.java
> +        return client.pollForResult(ByteBuffer.class).get().array();
Better yet, should we encode it before sending over the wire? e.g. Base64 or something, then we can simply send a string an not worry about this issue.

2019-02-08 09:43 UTC, prd-fox commented on enclave/enclave-websockets/src/main/java/com/jpmorgan/quorum/enclave/websockets/EnclaveEndpoint.java
> +        if (type == EnclaveRequestType.DEFAULT_PUBLIC_KEY) {
Are `if` statements really the best option here? A `switch` statement I think it the better alternative, either directly or passing off to private methods.
This method is doing too many things otherwise.

2019-02-08 09:43 UTC, prd-fox commented on enclave/enclave-websockets/src/main/java/com/jpmorgan/quorum/enclave/websockets/EnclaveEndpoint.java
> +        throw new UnsupportedOperationException(type + " is not supported");
Can we send back an error to the caller?

2019-02-08 09:43 UTC, prd-fox commented on enclave/enclave-websockets/src/main/java/com/jpmorgan/quorum/enclave/websockets/EnclaveRequestCodec.java
> +            if (type == ArgType.PUBLIC_KEY_LIST) {
A `switch` would be better here.

2019-02-11 12:18 UTC, Krish1979 approved these changes

2019-02-12 09:41 UTC, prd-fox approved these changes

2019-02-12 09:41 UTC, merged