Bump jetty version
Consensys-Incorporated/tessera pull request #968
Opened 2020-01-10 16:37 UTC by melowe

Fixes #958 . Change jersey tests to use grizzly as we need to migrate… all former javax prefixed group ids to use newer jakarta ones.

2020-01-10 16:52 UTC, SatpalSandhu61 submitted a review, later dismissed

2020-01-10 17:31 UTC, Krish1979 submitted a review, later dismissed

2020-01-13 10:26 UTC, chris-j-h requested changes
I think only one profile can be active at a time.  Check the Travis build report for the `Acceptance Tests Java 8` job and you'll see that now only the AWS acceptance tests are being run

2020-01-13 12:33 UTC, chris-j-h approved these changes

2020-01-13 12:34 UTC, merged